![imagen](./img/hundir-la-flota-juego-de-mesa.jpg)

En esta entrega vas a crear tu propio juego de **Hundir la flota** en Python. 
[Aquí](http://es.battleship-game.org/) podrás probarlo online.

### En clase
1. Crea la función `crear_tablero(tamaño)`, un tablero por defecto de 10x10 relleno del carácter "_" con numpy.
2. Crea la función `colocar_barco(barco, tablero)`, que recibirá la lista de casillas de un barco y el tablero donde colocarlo. Prueba primero a posicionar un par de barcos por ejemplo en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Crea la función `disparar(casilla, tablero)`, si el disparo acierta en un barco sustituye la O por una X (tocado), si es agua, sustituye la _ por una A (Agua). Prueba primero a disparar el barco de 2 casillas.
4. Crea la función `crear_barco(eslora)`, que deberá crear una lista de casillas de un barco en función a la eslora, de forma aleatoria.

### Proyecto individual
1. Crea la función `colocar_barcos(tablero)`, que deberá de colocar la lista de barcos generados de forma aleatoria (6 barcos en total (3 barcos de eslora 2, 2 de eslora 3 y 1 eslora 4)) ¡Mucho ojo con barcos que estén superpuestos (no pueden ocupar dos barcos la misma casilla) o barcos que se salgan del tablero!
2. Escribe el flujo completo del programa, con la dinámica de turnos y funcionalidades necesarios para jugar contra la máquina (dispara a tu tablero de forma aleatoria). Crea todas las funciones que necesites y aplica todo lo aprendido que te sea útil.
3. Encapsula todo en un `main.py` y un `utils.py` para ejecutarlo desde terminal.
4. Sube tu proyecto a un repositorio de github y prepara una demo (solo se podrá enseñar desde terminal) para la presentación de tu proyecto.

## Presentación
Cada uno realizará una presentación el **lunes 16 de junio**, donde se contarán con **10 minutos máximo**, importante ceñirse al tiempo. Se tendrá que enseñar:
1. El git clone del repositorio de github a tu ordenador y explicar las partes más relevantes del código.
2. Una demo donde se muestre el correcto funcionamiento del código para jugar, ejecutándose desde terminal.
3. Explicación de la lógica de las partes más relevantes del código desarrollado.

In [4]:
import numpy as np
np.__version__


'2.3.0'

In [1]:
!pip install numpy

In [5]:
type(np)

module

In [3]:
import numpy as np

In [11]:
np.array([[[[[1,2,3]]]]]).shape

(1, 1, 1, 1, 3)

In [12]:
np.array([[1],[2],[3]]).shape

(3, 1)

In [15]:
np.array([[1],[2],[3]])[2]

array([3])

In [18]:
array2 = np.array([[1,2,3,10],
         [4,5,6,20],
         [7,8,9,30]]) # (3,4)
array2

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30]])

In [45]:
array2

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30]])

In [53]:
array2[ -1::-10, 0::2]

array([[7, 9]])

In [ ]:
# 1 2 3
# 7 8 9

In [54]:
array2[-2::3,-3::-1] 

#

array([[5, 4]])

In [ ]:
# 30 8
# 10 2

In [ ]:
array2[1,2] # array2[1][2]

np.int64(6)

In [17]:
np.array([[1,2,3,10],
         [4,5,6,20],
         [7,8,9,30]]) # (3,4)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30]])

In [ ]:
np.array([[1,2,3],
         [4,5,6],
         [7,8,9]])

In [7]:
mi_array1 = np.array([[1,2,3], [4,5,6]])
mi_array1

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
mi_array1.shape

(2, 3)

In [9]:
mi_array1.ndim

2

In [5]:
[[1,2,3,4,5], [7]]

[[1, 2, 3, 4, 5], [7]]

In [20]:
np.full((10,10), ' ')

array([[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')